# Generated by Django 3.2.18 on 2023-04-21 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230421_0958'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Movie_Actors',
        ),
    ]
