# Generated by Django 3.2.18 on 2023-04-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctors',
            field=models.ManyToManyField(through='hospitals.Reservation', to='hospitals.Doctor'),
        ),
    ]
